// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5v5LYSC-lekDpHx9wNq0lw20Gep-wxWQ',
    appId: '1:878190453723:android:04a18ab9d65968c5313dfe',
    messagingSenderId: '878190453723',
    projectId: 'mclv-musicapp',
    storageBucket: 'mclv-musicapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-Y4Ie9hx0wb5DHuJ124magcig2TY9jg',
    appId: '1:878190453723:ios:e8bfc19e2b5f759f313dfe',
    messagingSenderId: '878190453723',
    projectId: 'mclv-musicapp',
    storageBucket: 'mclv-musicapp.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );
}